file_format: "1"
id: lily58
name: Lily58-Glow-ENC-W
type: shield
url: https://github.com/iasoren/Lily58-Glow-Enc-Wireless
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - lily58_left
  - lily58_right
