manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim/zmk
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk
      remote: infused-kim
      revision: my-changes/oled-ext-pwr
      clone-depth: 1
      import: app/west.yml
  self:
    path: config
