manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim/zmk-zephyr
  projects:
    - name: zmk
      remote: infused-kim
      revision: oled
      import: app/west.yml
  self:
    path: config
