manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim/zmk-zephyr/tree/v3.0.0%2Bzmk-fixes%2Bpd-oled
  projects:
    - name: zmk
      remote: infused-kim
      revision: v3.0.0+zmk-fixes+pd-oled
      import: app/west.yml
  self:
    path: config
