manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim/zmk-zephyr
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
     - name: zmk-zephyr
      remote: infused-kim
      revision: v3.0.0+zmk-fixes+pd-oled
      import: app/west.yml
  self:
    path: config
